engines:
  eslint:
    enabled: true
    channel: "stable"
    checks:
      import/extensions:
        enabled: false

  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
- "**.test.*"
- "testeFuncional/"
