engines:
  eslint:
    enabled: true
    channel: "stable"

  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
- "**.test.*"
