language: node_js
cache: yarn
node_js: '7'
jobs:
  include:
  - stage: lint
    script:
      - yarn lint
  - stage: unit tests
    script: yarn test
  - stage: deploy
    before_script: yarn build
    deploy:
      provider: firebase
      skip_cleanup: true
      on:
        branch: firebase_travis_tests