language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '7'
jobs:
  include:
  - stage: lint
    script:
      - yarn lint
  - stage: unit tests
    script: yarn test-coverage
  - stage: deploy
    before_script: yarn build
    deploy:
      provider: firebase
      skip_cleanup: true
      on:
        branch: master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a387d084c573fd34e585
    on_success: change
    on_failure: always
    on_start: always
