language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '7'
jobs:
  include:
  - stage: lint
    script:
      - yarn lint
  - stage: unit tests
    script: yarn test-coverage
  - stage: collect coverage
    script: CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < ./coverage/lcov.info
  - stage: deploy
    before_script: yarn build
    deploy:
      provider: firebase
      skip_cleanup: true
      on:
        branch: master
